// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Akka")]
[assembly: AssemblyCopyrightAttribute("Copyright © Aaron Stannard 2013-2015")]
[assembly: AssemblyVersionAttribute("0.3.3.0")]
[assembly: AssemblyFileVersionAttribute("0.3.3.0")]
